services:
  app:
    build:
      context: node
    image: alissonmartineli/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    container_name: app
    networks:
      - node-network
    depends_on:
      - db
    command: "node index.js"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    image: alissonmartineli/nginx-node
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
